<?xml version="1.0"?>
<testsuites name="Unknown Run" time="15" tests="5" failures="1" errors="1"><testsuite name="Module A" time="3" tests="2" failures="0" errors="0"><testcase name="test10" time="1"/><testcase name="test11" time="2"/></testsuite><testsuite name="Module B" time="3" tests="1" failures="0" errors="0"><testcase name="test20" time="3"/></testsuite><testsuite name="Module E" time="4" tests="1" failures="0" errors="1"><testcase name="test50" time="4"><error message="An exception was thrown!">An exception was thrown!</error></testcase></testsuite><testsuite name="Module F" time="5" tests="1" failures="1" errors="0"><testcase name="test60" time="5"><failure message="expected: 5, actual: 'six'">expected: 5, actual: 'six'</failure></testcase></testsuite></testsuites>